Gestion de thèses/HDR: tx_ligesttheses_pi1 Class Reference
tx_ligesttheses_pi1 Class Reference
Public Member Functions
main ($content, $conf)
Public Attributes
$prefixId = 'tx_ligesttheses_pi1'
$scriptRelPath = 'pi1/class.tx_ligesttheses_pi1.php'
$extKey = 'li_gest_theses'
$pi_checkCHash = true
Private Member Functions
rechercheFils ($pid_parent)
rechercherUidLangue ($uid, $sys_language_uid, $uid_parent, $texte_champ, $table, $nom_champ)
membre ($uid_membres)
encadrant ($uid_encadrants, $est_directeur)
equipe ($uid_equipes)
structure ($uid_structures)
rechercheStructuresFille ($id_parent)
resultat ($uid_resultats)
financement ($uid_financements)
Detailed Description
Definition at line 35 of file class.tx_ligesttheses_pi1.php.
Member Function Documentation
tx_ligesttheses_pi1::rechercheFils ($ pid_parent) [private]
Recherche des sous-dossiers contenant les membres du laboratoire...
Parameters:
$pid_parent identifiant du dossier à explorer
Returns:
Un tableau contenant tous les sous-dossiers trouvés...
Definition at line 47 of file class.tx_ligesttheses_pi1.php.
Referenced by main().
tx_ligesttheses_pi1::rechercherUidLangue ($ uid, $ sys_language_uid, $ uid_parent, $ texte_champ, $ table, $ nom_champ) [private]
Gestion du multilangue Cette fonction recherche le texte le plus approprié par rapport à la page chargée Cette fonction est utilisée à la suite d'une requête permettant de connaître les paramètres $uid, $sys_language_uid, $uid_parent et $texte_champ.
Parameters:
$uid L'identifiant de l'enregistrement pour lequel on recherche la meilleur traduction.
$sys_language_uid L'identifiant de la langue de l'enregistrement pour lequel on recherche la meilleur traduction.
$uid_parent L'identifiant du parent de l'enregistrement pour lequel on recherche la meilleur traduction.
$texte_champ La traduction de l'enregistrement pour lequel on recherche la meilleur traduction.
$table Le nom de la table dans laquel se trouve le champ à traduire
$nom_champ Le nom du champ à traduire
Returns:
Une chaîne de caractères contenant la traduction a afficher
Definition at line 98 of file class.tx_ligesttheses_pi1.php.
Referenced by main().
tx_ligesttheses_pi1::membre ($ uid_membres) [private]
Choix des membres Cette fonction permet de créer une contrainte concernant les membres
Parameters:
$uid_membres Chaîne de caractères contenant les identifiants des membres (uid) séparés par des virgules
Returns:
Une chaîne de caractères contenant une contrainte à rajouter à une requête
Definition at line 167 of file class.tx_ligesttheses_pi1.php.
Referenced by main().
tx_ligesttheses_pi1::encadrant ($ uid_encadrants, $ est_directeur) [private]
Choix des encadrants Cette fonction permet de créer une contrainte concernant les encadrants
Parameters:
$uid_encadrants Chaîne de caractères contenant les identifiants des encadrants (uid) séparés par des virgules
$est_directeur Indique si l'encadrant doit être ou non directeur de la thèse
Returns:
Une chaîne de caractères contenant une contrainte à rajouter à une requête
Definition at line 205 of file class.tx_ligesttheses_pi1.php.
Referenced by main().
tx_ligesttheses_pi1::equipe ($ uid_equipes) [private]
Choix des équipes Cette fonction permet de créer une contrainte concernant les équipes
Parameters:
$uid_equipes Chaîne de caractères contenant les identifiants des équipes (uid) séparés par des virgules
Returns:
Une chaîne de caractères contenant une contrainte à rajouter à une requête
Definition at line 252 of file class.tx_ligesttheses_pi1.php.
Referenced by main().
tx_ligesttheses_pi1::structure ($ uid_structures) [private]
Choix des structures Cette fonction permet de créer une contrainte concernant les structures
Parameters:
$uid_categories Chaîne de caractères contenant les identifiants des structures (uid) séparés par une virgule
Returns:
Une chaîne de caractères contenant une contrainte à rajouter à une requête
Definition at line 293 of file class.tx_ligesttheses_pi1.php.
References rechercheStructuresFille().
Referenced by main().
tx_ligesttheses_pi1::rechercheStructuresFille ($ id_parent) [private]
Recherche de structures filles
Parameters:
$id_parent identifiant de la structure principale
Returns:
Un tableau contenant toutes les sous-structures trouvées...
Definition at line 345 of file class.tx_ligesttheses_pi1.php.
Referenced by structure().
tx_ligesttheses_pi1::resultat ($ uid_resultats) [private]
Choix des résultats Cette fonction permet de créer une contrainte concernant les résultats
Parameters:
$uid_resultats Chaîne de caractères contenant les identifiants des résultats séparés par des virgules
Returns:
Une chaîne de caractères contenant une contrainte à rajouter à une requête
Definition at line 392 of file class.tx_ligesttheses_pi1.php.
Referenced by main().
tx_ligesttheses_pi1::financement ($ uid_financements) [private]
Choix des financements Cette fonction permet de créer une contrainte concernant les financements
Parameters:
$uid_financements Chaîne de caractères contenant les identifiants des financements séparés par des virgules
Returns:
Une chaîne de caractères contenant une contrainte à rajouter à une requête
Definition at line 430 of file class.tx_ligesttheses_pi1.php.
Referenced by main().
tx_ligesttheses_pi1::main ($ content, $ conf)
The main method of the PlugIn
Parameters:
string $content: The PlugIn content
array $conf: The PlugIn configuration
Returns:
The content that is displayed on the website
Definition at line 472 of file class.tx_ligesttheses_pi1.php.
References encadrant(), equipe(), financement(), membre(), rechercheFils(), rechercherUidLangue(), resultat(), and structure().
Member Data Documentation
tx_ligesttheses_pi1::$prefixId = 'tx_ligesttheses_pi1'
Definition at line 36 of file class.tx_ligesttheses_pi1.php.
tx_ligesttheses_pi1::$scriptRelPath = 'pi1/class.tx_ligesttheses_pi1.php'
Definition at line 37 of file class.tx_ligesttheses_pi1.php.
tx_ligesttheses_pi1::$extKey = 'li_gest_theses'
Definition at line 38 of file class.tx_ligesttheses_pi1.php.
tx_ligesttheses_pi1::$pi_checkCHash = true
Definition at line 39 of file class.tx_ligesttheses_pi1.php.
The documentation for this class was generated from the following file:
U:/Typo3/svntheses/trunk/li_gest_theses/pi1/class.tx_ligesttheses_pi1.php